# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('who', models.TextField(default=False)),
                ('type', models.TextField(default=False)),
                ('date', models.DateField()),
                ('second', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'db_table': 'run',
            },
        ),
    ]
