# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='route',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='run',
            name='who',
            field=models.TextField(default=''),
        ),
    ]
