# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtracker', '0002_auto_20160705_0546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['date', 'run_id']},
        ),
        migrations.AddField(
            model_name='run',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
