# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtracker', '0005_auto_20160705_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run',
            field=models.BooleanField(default=True),
        ),
    ]
