# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtracker', '0006_run_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='seconds',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='run',
            name='type',
            field=models.CharField(choices=[('', '-------'), ('couch25k', 'Couch25K'), ('hike', 'Hike'), ('walk', 'Walk')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='run',
            name='who',
            field=models.CharField(choices=[('', '-------'), ('david', 'David'), ('claire', 'Claire')], default='', max_length=6),
        ),
    ]
