# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtracker', '0008_auto_20160708_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='seconds',
            field=models.IntegerField(),
        ),
    ]
